<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'AssetsHandler\Module'                        => __DIR__ . '/Module.php',
    'AssetsHandler\Controller\AssetsHandlerController' => __DIR__ . '/src/AssetsHandler/Controller/AssetsHandlerController.php',
    'AssetsHandlerTest\Framework\TestCase'        => __DIR__ . '/tests/AssetsHandler/Framework/TestCase.php',
    'AssetsHandlerTest\SampleTest'                => __DIR__ . '/tests/AssetsHandler/SampleTest.php',
);
